(part "RAPC712TRP22X"
    (packageRef "RAPC712TRP22X")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "502-RAPC712TRP22X")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Switchcraft/RAPC712TRP22X?qs=vHuUswq2%252BszirK%2F7pueKKA%3D%3D")
    (property "Manufacturer_Name" "Switchcraft")
    (property "Manufacturer_Part_Number" "RAPC712TRP22X")
    (property "Description" "DC Power Connectors Right Angle PC Mount DC Power Jack, pin size 0.100"(2.5mm), packaged in a 22" reel")
    (property "Datasheet_Link" "https://www.mouser.co.uk/datasheet/2/393/rapc712x_cd-2943016.pdf")
    (property "symbolName1" "RAPC712TRP22X")
)
