(part "UJ20-C-H-G-MSMT-R-4C-P16-TR"
    (packageRef "UJ20CHGMSMTR4CP16TR")
    (interface
        (port "A1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "A4" (symbPinId 2) (portName "VBUS_1") (portType INOUT))
        (port "A5" (symbPinId 3) (portName "CC1") (portType INOUT))
        (port "A6" (symbPinId 4) (portName "DP1") (portType INOUT))
        (port "A7" (symbPinId 5) (portName "DN1") (portType INOUT))
        (port "A8" (symbPinId 6) (portName "SBU1") (portType INOUT))
        (port "A9" (symbPinId 7) (portName "VBUS_2") (portType INOUT))
        (port "A12" (symbPinId 8) (portName "GND_2") (portType INOUT))
        (port "B5" (symbPinId 9) (portName "CC2") (portType INOUT))
        (port "B6" (symbPinId 10) (portName "DP2") (portType INOUT))
        (port "B7" (symbPinId 11) (portName "DN2") (portType INOUT))
        (port "B8" (symbPinId 12) (portName "SBU2") (portType INOUT))
        (port "MH1" (symbPinId 13) (portName "MH_1") (portType INOUT))
        (port "MH2" (symbPinId 14) (portName "MH_2") (portType INOUT))
        (port "MH3" (symbPinId 15) (portName "MH_3") (portType INOUT))
        (port "MH4" (symbPinId 16) (portName "MH_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "UJ20-C-H-G-MSMT-R-4C-P16-TR")
    (property "Description" "UJ20-C-H-G-MSMT-R-4C-P16-TR - Type C, USB 2.0, 480 Mbps, 20 Vdc, 3 A, Horizontal, Mid Mount SMT, SMT Contacts, Gold Flash, Recessed Lip, 16 Pins, Ultra Low Profile 1.56mm, USB Receptacle")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/uj20-c-h-g-msmt-r-4c-p16-tr.pdf")
    (property "symbolName1" "UJ20-C-H-G-MSMT-R-4C-P16-TR")
)
